apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web1
  labels:
    app: web1
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: php-apache
          image: esimonetti/sugardockerized:php7.1-apache-1.16
          name: sugar-web1
          ports:
          - containerPort: 80
          volumeMounts:
          - name: hostvol
            mountPath: /var/www/html/
      volumes:
        - name: hostvol
          hostPath:
            path: /Users/vkobilanksy/jx-sugar-docker/data/app/sugar