apiVersion: v1
kind: Service
metadata:
  name: sugar-redis
  labels:
    app: sugar-redis
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: sugar-redis
    tier: backend
