apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sugar-redis
  labels:
    app: sugar-redis
spec:
  selector:
    matchLabels:
      app: sugar-redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sugar-redis
        tier: backend
    spec:
      containers:
      - name: sugar-redis
        image: k8s.gcr.io/redis:e2e  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

