apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f php71.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cron
  name: cron
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cron
    spec:
      containers:
      - image: esimonetti/sugardockerized:php7.1-cron-1.16
        name: sugar-cron
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: cron-claim0
      restartPolicy: Always
      volumes:
      - name: cron-claim0
        persistentVolumeClaim:
          claimName: cron-claim0
status: {}
