apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f php71.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: permissions
  name: permissions
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: permissions
    spec:
      containers:
      - image: esimonetti/sugardockerized:permissions-1.17
        name: sugar-permissions
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: permissions-claim0
      restartPolicy: Always
      volumes:
      - name: permissions-claim0
        persistentVolumeClaim:
          claimName: permissions-claim0
status: {}
