apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.18.0 ()
  labels:
    io.kompose.service: web1
    kompose.service.type: LoadBalancer
  name: web1
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: web1
status:
  loadBalancer: {}
