kind: PersistentVolume
apiVersion: v1
metadata:
  name: web1-persistent-volume
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/vkobilanksy/jx-sugar-docker/data/app"